### ISSUE TITLE
Address Locator not returning results

### ISSUE THREAD

**Issue by vcoelho** [EsriCanada/municipal-government-services#12]
Need to add the field "World" to the template when using Esri's world geocode service.

Here's how it should look like : LocatorFieldValues: ["CAN.StreetName" , "CAN.PointAddress", "CAN.StreetAddress", "CAN.PostalExt","World"]

**Comment by dblanchardDev** [comment]
As ArcGIS Online has changed the naming convention of its locators, changes to the configuration file are required in order to continue using the address search capabilities of the application.

In the _/js/config.js_ file, modify the `LocatorFieldValues` field from
`["CAN.StreetName", "CAN.PointAddress", "CAN.StreetAddress", "CAN.PostalExt"]`
to
`["World"]`

---

#### Localisateur d’adresse ne retourne pas de résultats
Due à un changement dans la nomenclature des localisateurs d’ArcGIS Online, un changement doit être apporté au fichier de configuration afin de continuer d’utiliser la fonction de recherche pas adresse.

Dans le fichier _/js/config.js_, modifier le champ `LocatorFieldValues` de
`["CAN.StreetName", "CAN.PointAddress", "CAN.StreetAddress", "CAN.PostalExt"]`
à
`["World"]`
